version: '3'

dotenv: ['.env.deploy']

vars:
  DOCKER_IMAGE: nnvt-site

tasks:
  install:
    desc: Install npm dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json

  dev:
    desc: Start Astro dev server (http://localhost:4321)
    deps: [install]
    cmds:
      - npm run dev

  build:
    desc: Build static site to dist/
    deps: [install]
    cmds:
      - npm run build

  preview:
    desc: Preview production build locally (http://localhost:4321)
    deps: [build]
    cmds:
      - npm run preview

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf dist node_modules .astro

  docker:build:
    desc: Build Docker production image
    cmds:
      - docker build -t {{.DOCKER_IMAGE}}:latest .

  docker:dev:
    desc: Start dev server via Docker Compose
    cmds:
      - docker compose -f docker-compose.yml --profile dev up

  docker:prod:
    desc: Build and start production container locally (http://localhost:8080)
    deps: [docker:build]
    cmds:
      - docker compose -f docker-compose.yml --profile prod up -d

  docker:stop:
    desc: Stop all local Docker Compose services
    cmds:
      - docker compose -f docker-compose.yml --profile dev --profile prod down

  deploy:
    desc: Build image, transfer to server, and deploy
    deps: [docker:build]
    cmds:
      - docker save {{.DOCKER_IMAGE}}:latest -o {{.IMAGE_FILE}}
      - scp {{.IMAGE_FILE}} {{.REMOTE_USER}}@{{.REMOTE_HOST}}:{{.REMOTE_DIR}}
      - bash deploy.sh
      - rm -f {{.IMAGE_FILE}}

  lint:
    desc: Run Astro check (type checking)
    deps: [install]
    cmds:
      - npx astro check
